name: ffmpeg_cmds
description: ffmpeg commands for dart
version: 0.0.1
repository: https://github.com/thitlwincoder/ffmpeg_cmds
environment:
  sdk: "^3.3.0"

funding:
  - https://paypal.me/thitlwinsoe260
  - https://ko-fi.com/thitlwincoder

dev_dependencies:
  very_good_analysis: ^5.1.0

dependencies:
  args: ^2.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  html: ^0.15.4
  html2md: ^1.3.1
  recase: ^4.1.0
