name: ffmpeg_cmds
description: ffmpeg commands for dart
version: 0.0.1
repository: https://github.com/thitlwincoder/ffmpeg_cmds
environment:
  sdk: "^3.3.0"

funding:
  - https://paypal.me/thitlwinsoe260
  - https://ko-fi.com/thitlwincoder

dev_dependencies:
  very_good_analysis: ^5.1.0
